language: python
python:
- "3.4"
- "3.5"
- "3.6"
before_install:
- pip install poetry
install:
- poetry install -v
script:
- nosetests
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == "3.6"
env:
  global:
  - secure: "fzUeRwFVMfjOHLwIZmhNhD1wN1OWNX2oO4iokajEzWl3A+OLOPphicT9yLqxFM9WcGVu0FXNStqhb5yCXduQg5hGrTzndOXmBGHubhJzO6SfXYFNEPtE7DSOcZOOQ3UfFjy9F645yBnoVGtD3n02tgfKbLlHZEH5WL1qe7clC9AU2hD4xrIxdv7KyL9TB96EnkvBboz0FJyoUucPCL8GbymJCvfcyLtR5VDp29XJONsTxliJK29VXkxqCqHbee0h3qlhnoLX6Ty1l47DYNxQQauti843LEmxM2+2eq/r4dLuS50erpKJBr9u/mHRdx6o5vnu1BYD1Nkqt+Dn99CkB5oU+1/AVMUZKH2j74ft7BrnO22EeMbzO3T0Oj5MOWqAZCmZ+ywsL2UphIS/D2NI57gQ5hlBwW40Pzvo0ajRJKQTk2Y/Cw7m+8GxourOKIejRRcysWUaFzp6gIT1ydtPrDocccePAmpoQyFXRvERGRCn0Rg9vV12WMe2cO8OdrNteQIC4RfL/T5aJrkghvqyLxZx5RXx93Iscv7AKhFiHEwa/dJev1nPlwdrPxPTFhKK48M2rD7ebSZ699w+FRYpPXFixG1A/3c5PzQdKNDGJiofm3Lb36Gq3IIjLH5Ws49BLhkNQNGi1GCLNp4rMJFJK73N5UHjEaIb5ril7u7pZpQ="
  - secure: "5W3UhbwVYZGjfx1CUZsl5LEACr8h2FE1EyiE+pXM/y4NjdR6+cAj3HOs+Uq3rNl8ticfRA/ImPK/I/LrD+LrBY0o5SVNFSe9RBl8EfSHAREAW4fQFKEyFvwXPJc6PCr0y6KYkGu9yjGOZUSoilTiv5wJrKtijhBvcrky5T6pYMmD1c+fGvzPiOJ9w34ms7wvNq83k0X+5TFkd1V4iLjI3Fax1vqFKoY/lV0RqnlEA3oYQq4NiN++vT0foFG5d3GsgvUgId4Lya9xQplhisrydB3jkri8BqPBXwVuRD24OErQqSlYceJ99W42xhtpuGapXaAUpFYQjsRpgadqXaZH3pQAAey3iScXoeEpBsqRksK8a8b7Rl3E5Yztr/fn8yFyq3deiu4WXS9nc1gFus3J07Cs+DsJXet68DbmaO9ILTjbNvUaEacjxZZqY0+rYVqay4oA0z42UD8L2X1c38u4UxDC6WfET1qtBQ72M/Cwke2IAjRzxN4/cwa7gk6jZhFl0JME5qoalCgHNI+772pKKrumQb63XTFLRDG62gDA4GUEqYRyp30/muStNXdXbL92ZVEutIlLxkCQi/HyRctIbdo/n0KDg6bxQ/yq2AZTE87pPUa4un6+gzV2niRLwKqJDRh2Y89SXy9zgyu1xNR/c2Stc8W29txBb3y8i+68kXo="
