language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip install poetry
install:
  - poetry install -v
script:
  - nosetests
before_deploy:
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
  - poetry build
