language: python
python:
- "3.4"
- "3.5"
- "3.6"
before_install:
- pip install poetry
install:
- poetry install -v
script:
- nosetests
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.6"
env:
  global:
  - secure: "sq+GfYaUtQm9yMI/las3op3cQVDdFdWspVwf0+8INMN8/AxeKXxJIJAh6h2u99CocPqcdT9eII+a/HEgl/Io5jBU1shb4+Ccu04ebNZHSHgKjmcX09GDzML3HwXJkCejN0O5NItMRAsGMJ1IdpN3y60BKaTTA3EYGMEyx5Aez8fE1d+lci5JC1OWX4DwEaeOiX991QnConjnvX6alciU7CJNfatkvzeEjBLzGeIYX7IB5qggPJAQiJc1DkgAXRuB+qmyG+MNJDz8bHXM4mZb09pU9glKMIWeCPZ3fnO6BVsCEfAL46hD70eUDbr421t2yPRUwm42EX5i549H5C7DPF7JuqSVGgAB4E8lv1Qm7QyZ1TZ2+pVS8GV7awNze3VtXOmL/dKsvLNGdLuhkW543lSWwcVHoaoIbSK8wgYM81sT7xEO8bLv5EzNLJyvxkgqY3FOM8R6HmcOo7RxQb9UwM+A7qgu1mca/bKZzomCCUokBGxU6KZrxqpbv1sh5L9NfvR4uCXtyyOA8Oe850xupsgk/C7nqbpBIgMRMkzEKFgtb+ErpZQ/EByi+P6uS3ftfFszr8gd4mlqySGF4i8mB+6V0SjfG/K0dsgEVki943y4bQ+R1FO2F8c3+8l6DJ7eiL5l8Eulk2u0Eo9+uujmVzS22rlfqr1GH7ErMRY2jBg="
  - secure: "xQfIkiOZbKDI0sHvt6KqknBeDMUM5qX+lMcXMn7zGXjlsaNjNeVkUJ5LwaChAf4aJOpzNJbgnF2LCZsUDx7gF1ZwDEmen9CEMp++cfLzjm8OkcuBUyMTyCW/Um1hWRqhQp1iFM9+Tl21o5s29zGB7wIuRUHM5pJWRqfO1CDNFqbqvbcgjNRWRmnkHIF0vH6rfeiQdY8884EMxUF187RDbay5cEIZpu1saMu7UkZg+PV9IfJPX0eNtclAh4/zj94Q/axmqqTBNs4DJLWtiKA0fMh6usulBosxldPALqGuTs6Haj5pIXdHRtgxhcHquEgyWpGKul91Zct7MGFTIp1fz9UvvwnftFFgfOQahkd2VOdVQ+o0tCURWUoVxoXCtDdElac0KFiQNZriJcdumArp9AbP9smuIOKo2gzjguCUFgT8icjgOiIYtT6xkIi2PaZexf8eDTFMUKhcUnWgIOkVFiZX0yH2e731Njl3oSD97KBuFfsjNaxy/XWOf2WeWKf8Avckf1qSo9W6ALvvS4ggodCZfUpM1Hm1fFA8kYoYXguKo4acer0Fi8hLsJLHVoMtlSXiVlArWN0uWQ7fs2D2wz2UPuSiBAZb8Ik2Ig15tK8pntz7duJdPJPXBWLJFjzTM1HuuHkTMlzB4bpPCJvM+YD4aXG6U4L/LcgJ62xQDpA="
